apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server
  labels:
    app: my-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-server
  template:
    metadata:
      labels:
        app: my-server
    spec:
      containers:
      - name: my-server
        image: quay.io/nunnatsa/demoserver:v2
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-server-service
spec:
  selector:
    app: my-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
